<?php

use Illuminate\Database\Seeder;
use App\Dish;
use Illuminate\Support\Facades\DB;

class dishes_seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // factory(Dish::class, 100)->create();

        DB::table('dishes')->insert([
            [
                'restaurant_id' => 1,
                'name' => 'Marinara',
                'price' => '6',
                'visibility' => true,
                'genre_id' => 3,
                'description' => "Pomodoro S.Marzano, aglio, origano, basilico, olio Evo",
                'image_url' => 'pizza-marinara.jpg',
            ],
            [
                'restaurant_id' => 1,
                'name' => 'Margherita',
                'price' => '6',
                'visibility' => true,
                'genre_id' => 3,
                'description' => "Pomodoro S.Marzano, Fior di Latte, basilico, olio Evo",
                'image_url' => 'pizza-margherita.jpg',
            ],
            [
                'restaurant_id' => 1,
                'name' => 'Americana',
                'price' => '8',
                'visibility' => true,
                'genre_id' => 3,
                'description' => "Pomodoro S.Marzano, Fior di Latte, Würstel, Patatine, basilico, olio Evo",
                'image_url' => 'wurstel-patatine.jpg',
            ],
            [
                'restaurant_id' => 1,
                'name' => 'Napoli',
                'price' => '8',
                'visibility' => true,
                'genre_id' => 3,
                'description' => "Pomodoro S.Marzano DOP, Fior di Latte, Olive di Gaeta, Acciughe di Sciacca",
                'image_url' => 'pizza-pachino.jpg',
            ],
            [
                'restaurant_id' => 1,
                'name' => 'Bufalina',
                'price' => '8',
                'visibility' => true,
                'genre_id' => 3,
                'description' => "Pomodoro S.Marzano DOP, Bufala Campana DOP, basilico, olio Evo",
                'image_url' => 'pizza-Bufalina.jpg',
            ],
            [
                'restaurant_id' => 1,
                'name' => 'Carbonara',
                'price' => '10',
                'visibility' => true,
                'genre_id' => 2,
                'description' => "Spaghetti,Guanciale, Tuorlo d'Uovo, Pecorino romano DOP",
                'image_url' => 'carbonara.jpg',
            ],
            [
                'restaurant_id' => 1,
                'name' => 'Amatriciana',
                'price' => '10',
                'visibility' => true,
                'genre_id' => 2,
                'description' => "Spaghetti,Guanciale, Pomodoro, Pecorino romano DOP",
                'image_url' => 'amatriciana.jpg',
            ],
            [
                'restaurant_id' => 1,
                'name' => 'Cacio e Pepe',
                'price' => '10',
                'visibility' => true,
                'genre_id' => 2,
                'description' => "Spaghetti,
                Pecorino romano DOP, Pepe",
                'image_url' => 'caciopepe.jpg',
            ],
            [
                'restaurant_id' => 2,
                'name' => 'Carbonara',
                'price' => '10',
                'visibility' => true,
                'genre_id' => 2,
                'description' => "Spaghetti,Guanciale, Tuorlo d'Uovo, 
                Pecorino romano DOP",
                'image_url' => 'carbonara.jpg',
            ],
            [
                'restaurant_id' => 2,
                'name' => 'Amatriciana',
                'price' => '10',
                'visibility' => true,
                'genre_id' => 2,
                'description' => "Spaghetti,Guanciale, Pomodoro, 
                Pecorino romano DOP",
                'image_url' => 'amatriciana.jpg',
            ],
            [
                'restaurant_id' => 2,
                'name' => 'Cacio e Pepe',
                'price' => '10',
                'visibility' => true,
                'genre_id' => 2,
                'description' => "Spaghetti,
                Pecorino romano DOP, Pepe",
                'image_url' => 'caciopepe.jpg',
            ],
            [
                'restaurant_id' => 2,
                'name' => 'Salmone al pepe Rosa',
                'price' => '12',
                'visibility' => true,
                'genre_id' => 5,
                'description' => "Trancio di salmone di Alaska, prezzemolo,
                olio Extra Vergine, Pepe Rosa",
                'image_url' => 'salmone.jpg',
            ],
            [
                'restaurant_id' => 2,
                'name' => 'Tartare di Tonno',
                'price' => '13',
                'visibility' => true,
                'genre_id' => 5,
                'description' => "Tartare di Tonno abbattuto, olio Evo, semi di papavero",
                'image_url' => 'tartare.jpg',
            ],
            [
                'restaurant_id' => 2,
                'name' => 'Scaloppine di Pollo al Limone',
                'price' => '13',
                'visibility' => true,
                'genre_id' => 4,
                'description' => "Fettine di pollo marinate al limone, olio, prezzemolo",
                'image_url' => 'scaloppine.webp',
            ],
            [
                'restaurant_id' => 2,
                'name' => 'Petti di Tacchino alla Bolognese',
                'price' => '14',
                'visibility' => true,
                'genre_id' => 4,
                'description' => "Tacchino, Prosciutto crudo, Parmigiano Reggiano DOP, Marsala, Tartufo Nero",
                'image_url' => 'tacchino.webp',
            ],
            [
                'restaurant_id' => 2,
                'name' => 'Patatine Fritte',
                'price' => '4',
                'visibility' => true,
                'genre_id' => 7,
                'description' => "Patatine, Sale",
                'image_url' => 'patate-fritte.jpg',
            ],
            [
                'restaurant_id' => 2,
                'name' => 'Verdure Grigliate',
                'price' => '5',
                'visibility' => true,
                'genre_id' => 7,
                'description' => "Zucchine, Melanzane, Zucca, Peperoni, Olio, Sale, Prezzemolo",
                'image_url' => 'verdure.jpg',
            ],
            [
                'restaurant_id' => 2,
                'name' => 'Patate al Forno',
                'price' => '5',
                'visibility' => true,
                'genre_id' => 7,
                'description' => "Patate, Rosmarino, Olio, Sale",
                'image_url' => 'forno.webp',
            ],
            [
                'restaurant_id' => 3,
                'name' => 'Scaloppine di Pollo al Limone',
                'price' => '13',
                'visibility' => true,
                'genre_id' => 4,
                'description' => "Fettine di pollo marinate al limone, olio, prezzemolo",
                'image_url' => 'scaloppine.webp',
            ],
            [
                'restaurant_id' => 3,
                'name' => 'Petti di Tacchino alla Bolognese',
                'price' => '14',
                'visibility' => true,
                'genre_id' => 4,
                'description' => "Tacchino, Prosciutto crudo, Parmigiano Reggiano DOP, Marsala, Tartufo Nero",
                'image_url' => 'tacchino.webp',
            ],
            [
                'restaurant_id' => 3,
                'name' => 'Classico',
                'price' => '6',
                'visibility' => true,
                'genre_id' => 6,
                'description' => "Pane al Sesamo, Hamburger di Fassona 320g, Insalata, Pomodoro, *salse",
                'image_url' => 'burger.jpg',
            ],
            [
                'restaurant_id' => 3,
                'name' => 'ChickenBurger',
                'price' => '6',
                'visibility' => true,
                'genre_id' => 6,
                'description' => "Pane al Sesamo, Petto di Pollo impanato, Insalata, Pomodoro, *salse",
                'image_url' => 'burger.jpg',
            ],
            [
                'restaurant_id' => 3,
                'name' => 'BaconBurger',
                'price' => '6',
                'visibility' => true,
                'genre_id' => 6,
                'description' => "Pane al Sesamo, Hamburger di Maiale, Formaggio, Bacon, *salse",
                'image_url' => 'burger.jpg',
            ],
            [
                'restaurant_id' => 4,
                'name' => 'Marinara',
                'price' => '6',
                'visibility' => true,
                'genre_id' => 3,
                'description' => "Pomodoro S.Marzano, aglio, origano, basilico, olio Evo",
                'image_url' => 'pizza-marinara.jpg',
            ],
            [
                'restaurant_id' => 4,
                'name' => 'Margherita',
                'price' => '6',
                'visibility' => true,
                'genre_id' => 3,
                'description' => "Pomodoro S.Marzano, Fior di Latte, basilico, olio Evo",
                'image_url' => 'pizza-margherita.jpg',
            ],
            [
                'restaurant_id' => 4,
                'name' => 'Americana',
                'price' => '8',
                'visibility' => true,
                'genre_id' => 3,
                'description' => "Pomodoro S.Marzano, Fior di Latte, Würstel, Patatine, basilico, olio Evo",
                'image_url' => 'wurstel-patatine.jpg',
            ],
            [
                'restaurant_id' => 4,
                'name' => 'Napoli',
                'price' => '8',
                'visibility' => true,
                'genre_id' => 3,
                'description' => "Pomodoro S.Marzano DOP, Fior di Latte, Olive di Gaeta, Acciughe di Sciacca",
                'image_url' => 'pizza-pachino.jpg',
            ],
            [
                'restaurant_id' => 4,
                'name' => 'Bufalina',
                'price' => '8',
                'visibility' => true,
                'genre_id' => 3,
                'description' => "Pomodoro S.Marzano DOP, Bufala Campana DOP, basilico, olio Evo",
                'image_url' => 'pizza-Bufalina.jpg',
            ],
            [
                'restaurant_id' => 4,
                'name' => 'Focaccia',
                'price' => '5',
                'visibility' => true,
                'genre_id' => 3,
                'description' => "Focaccia, Sale, Olio, ingredienti a scelta",
                'image_url' => 'pizza-focaccia.jpg',
            ],
            [
                'restaurant_id' => 5,
                'name' => 'Temaki Roll',
                'price' => '5',
                'visibility' => true,
                'genre_id' => 5,
                'description' => "Salmone, Riso, Avocado, Philadelphia, Alga Nori, Maionese",
                'image_url' => 'temaki.webp',
            ],
            [
                'restaurant_id' => 5,
                'name' => 'Sashimi',
                'price' => '12',
                'visibility' => true,
                'genre_id' => 5,
                'description' => "Salmone o Tonno fresco abbattuto con Salsa di Soia agli Agrumi",
                'image_url' => 'sashimi.jpg',
            ],
            [
                'restaurant_id' => 5,
                'name' => 'Uramaki Roll',
                'price' => '8',
                'visibility' => true,
                'genre_id' => 5,
                'description' => "Roll di Riso con Salmone, Tonno o Gamberi, Avocado",
                'image_url' => 'uramaki.jpg',
            ],
            [
                'restaurant_id' => 6,
                'name' => 'Churrasco',
                'price' => '10',
                'visibility' => true,
                'genre_id' => 4,
                'description' => "Carne di Vitello e Maiale alla brace con verdure",
                'image_url' => 'churrasco.jpg',
            ],
            [
                'restaurant_id' => 6,
                'name' => 'Barbecue',
                'price' => '10',
                'visibility' => true,
                'genre_id' => 4,
                'description' => "Grigliata di carne mista",
                'image_url' => 'churrasco.jpg',
            ],
            [
                'restaurant_id' => 6,
                'name' => 'BaconBurger',
                'price' => '8',
                'visibility' => true,
                'genre_id' => 6,
                'description' => "Pane al Sesamo, Hamburger di Maiale, Formaggio, Bacon, *salse",
                'image_url' => 'burger.jpg',
            ],
            [
                'restaurant_id' => 6,
                'name' => 'Tagliata ai Ferri',
                'price' => '9',
                'visibility' => true,
                'genre_id' => 4,
                'description' => "Tagliata di Carne scottata alla piastra",
                'image_url' => 'churrasco.jpg',
            ],
            [
                'restaurant_id' => 7,
                'name' => 'Sacher Torte',
                'price' => '16',
                'visibility' => true,
                'genre_id' => 9,
                'description' => "Torta Sacher farcita con marmellata alle pesche, ricoperta di cioccolato fondente",
                'image_url' => 'sacher.jpg',
            ],
            [
                'restaurant_id' => 8,
                'name' => 'Spaghetti al pesto di Rucola',
                'price' => '7',
                'visibility' => true,
                'genre_id' => 2,
                'description' => "Spaghetti integrali, pesto di rucola, olio, mandorle",
                'image_url' => 'sacher.jpg',
            ],
            [
                'restaurant_id' => 8,
                'name' => 'Burger di Ceci',
                'price' => '6',
                'visibility' => true,
                'genre_id' => 7,
                'description' => "Burger di ceci alla piastra con spinaci",
                'image_url' => 'ceci.jpg',
            ],
            [
                'restaurant_id' => 8,
                'name' => 'Involtini di Melanzane al forno',
                'price' => '8',
                'visibility' => true,
                'genre_id' => 7,
                'description' => "Involtini di Melanzane con Pomodoro e Zucca",
                'image_url' => 'involtini.jpg',
            ],
            [
                'restaurant_id' => 9,
                'name' => 'Carbonara',
                'price' => '10',
                'visibility' => true,
                'genre_id' => 2,
                'description' => "Spaghetti,Guanciale, Tuorlo d'Uovo, 
                Pecorino romano DOP",
                'image_url' => 'carbonara.jpg',
            ],
            [
                'restaurant_id' => 9,
                'name' => 'Amatriciana',
                'price' => '10',
                'visibility' => true,
                'genre_id' => 2,
                'description' => "Spaghetti,Guanciale, Pomodoro, 
                Pecorino romano DOP",
                'image_url' => 'amatriciana.jpg',
            ],
            [
                'restaurant_id' => 9,
                'name' => 'Cacio e Pepe',
                'price' => '10',
                'visibility' => true,
                'genre_id' => 2,
                'description' => "Spaghetti,
                Pecorino romano DOP, Pepe",
                'image_url' => 'caciopepe.jpg',
            ],
            [
                'restaurant_id' => 9,
                'name' => 'Scaloppine di Pollo al Limone',
                'price' => '13',
                'visibility' => true,
                'genre_id' => 4,
                'description' => "Fettine di pollo marinate al limone, olio, prezzemolo",
                'image_url' => 'scaloppine.webp',
            ],
            [
                'restaurant_id' => 9,
                'name' => 'Petti di Tacchino alla Bolognese',
                'price' => '14',
                'visibility' => true,
                'genre_id' => 4,
                'description' => "Tacchino, Prosciutto crudo, Parmigiano Reggiano DOP, Marsala, Tartufo Nero",
                'image_url' => 'tacchino.webp',
            ],
            [
                'restaurant_id' => 9,
                'name' => 'Salmone al pepe Rosa',
                'price' => '12',
                'visibility' => true,
                'genre_id' => 5,
                'description' => "Trancio di salmone di Alaska, prezzemolo,
                olio Extra Vergine, Pepe Rosa",
                'image_url' => 'salmone.jpg',
            ],
            [
                'restaurant_id' => 9,
                'name' => 'Tartare di Tonno',
                'price' => '13',
                'visibility' => true,
                'genre_id' => 5,
                'description' => "Tartare di Tonno abbattuto, olio Evo, semi di papavero",
                'image_url' => 'tartare.jpg',
            ],
            [
                'restaurant_id' => 9,
                'name' => 'Supplì',
                'price' => '6',
                'visibility' => true,
                'genre_id' => 8,
                'description' => "Supplì di riso, sugo all'amatriciana, mozzarella campana",
                'image_url' => 'frittosuppli.jpg',
            ],
            [
                'restaurant_id' => 9,
                'name' => 'Verdure Fritte',
                'price' => '6',
                'visibility' => true,
                'genre_id' => 8,
                'description' => "Carote, Zucchine e Melanzane in pastella",
                'image_url' => 'frittoverdure.jpg',
            ],
            [
                'restaurant_id' => 9,
                'name' => 'Pasta Fritta',
                'price' => '6',
                'visibility' => true,
                'genre_id' => 8,
                'description' => "Pasta alle zucchine fritta con pancetta",
                'image_url' => 'fritto-pasta.jpg',
            ],
            [
                'restaurant_id' => 9,
                'name' => 'Fritto Misto',
                'price' => '6',
                'visibility' => true,
                'genre_id' => 8,
                'description' => "Fritto misto di mare",
                'image_url' => 'fritto-misto.jpg',
            ],
            [
                'restaurant_id' => 10,
                'name' => 'Classico',
                'price' => '6',
                'visibility' => true,
                'genre_id' => 6,
                'description' => "Pane al Sesamo, Hamburger di Fassona 320g, Insalata, Pomodoro, *salse",
                'image_url' => 'burger.jpg',
            ],
            [
                'restaurant_id' => 10,
                'name' => 'ChickenBurger',
                'price' => '6',
                'visibility' => true,
                'genre_id' => 6,
                'description' => "Pane al Sesamo, Petto di Pollo impanato, Insalata, Pomodoro, *salse",
                'image_url' => 'burger.jpg',
            ],
            [
                'restaurant_id' => 10,
                'name' => 'BaconBurger',
                'price' => '6',
                'visibility' => true,
                'genre_id' => 6,
                'description' => "Pane al Sesamo, Hamburger di Maiale, Formaggio, Bacon, *salse",
                'image_url' => 'burger.jpg',
            ],
            [
                'restaurant_id' => 10,
                'name' => 'Tagliata ai Ferri',
                'price' => '9',
                'visibility' => true,
                'genre_id' => 4,
                'description' => "Tagliata di Carne scottata alla piastra",
                'image_url' => 'churrasco.jpg',
            ],
            [
                'restaurant_id' => 10,
                'name' => 'Supplì',
                'price' => '6',
                'visibility' => true,
                'genre_id' => 8,
                'description' => "Supplì di riso, sugo all'amatriciana, mozzarella campana",
                'image_url' => 'frittosuppli.jpg',
            ],
            [
                'restaurant_id' => 10,
                'name' => 'Verdure Fritte',
                'price' => '6',
                'visibility' => true,
                'genre_id' => 8,
                'description' => "Carote, Zucchine e Melanzane in pastella",
                'image_url' => 'frittoverdure.jpg',
            ],
            [
                'restaurant_id' => 10,
                'name' => 'Pasta Fritta',
                'price' => '6',
                'visibility' => true,
                'genre_id' => 8,
                'description' => "Pasta alle zucchine fritta con pancetta",
                'image_url' => 'fritto-pasta.jpg',
            ],
            [
                'restaurant_id' => 10,
                'name' => 'Fritto Misto',
                'price' => '6',
                'visibility' => true,
                'genre_id' => 8,
                'description' => "Fritto misto di mare",
                'image_url' => 'fritto-misto.jpg',
            ],
            [
                'restaurant_id' => 10,
                'name' => 'Barbecue',
                'price' => '10',
                'visibility' => true,
                'genre_id' => 4,
                'description' => "Grigliata di carne mista",
                'image_url' => 'churrasco.jpg',
            ],
        ]);
    }
}
